# Generated by Django 3.1.5 on 2021-03-16 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categorias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoria Proveedores',
                'verbose_name_plural': 'Categorias Proveedores',
            },
        ),
        migrations.CreateModel(
            name='proveedoresModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(auto_created=True, max_length=15, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('ciudad', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=100)),
                ('tfno', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electronico')),
                ('web', models.URLField(verbose_name='Página web')),
                ('descripcion', models.TextField(max_length=255)),
                ('img_productos', models.ImageField(default='proveedores/default.png', upload_to='proveedores/imgs')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProveedoresApp.categorias')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['created'],
            },
        ),
    ]
