# Generated by Django 3.1.5 on 2021-03-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProveedoresApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedoresmodel',
            name='img_productos',
            field=models.ImageField(default='proveedores/default.png', null=True, upload_to='proveedores/imgs'),
        ),
        migrations.AlterField(
            model_name='proveedoresmodel',
            name='web',
            field=models.URLField(null=True, verbose_name='Página web'),
        ),
    ]
