# Generated by Django 3.1.5 on 2021-03-16 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProveedoresApp', '0003_remove_proveedoresmodel_img_productos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedoresmodel',
            name='slug',
            field=models.SlugField(auto_created=True, blank=True, max_length=15, unique=True),
        ),
    ]
