# Generated by Django 3.1.5 on 2021-03-16 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProveedoresApp', '0004_auto_20210316_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedoresmodel',
            name='img_proveedor',
            field=models.ImageField(default='proveedores/default.png', null=True, upload_to='proveedores/imgs'),
        ),
    ]
