# Generated by Django 3.1.5 on 2021-03-16 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProveedoresApp', '0005_proveedoresmodel_img_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='prodcutosPro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('img_producto', models.ImageField(default='productos/default.png', null=True, upload_to='productos/proveedores')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.AddField(
            model_name='proveedoresmodel',
            name='productos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ProveedoresApp.prodcutospro'),
        ),
    ]
