# Generated by Django 3.1.5 on 2021-03-17 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProveedoresApp', '0006_auto_20210316_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='productosIMG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagenes', models.ImageField(default='proveedores/default.png', null=True, upload_to='proveedores/imgs')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.AlterField(
            model_name='proveedoresmodel',
            name='productos',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='prodcutosPro',
        ),
        migrations.AddField(
            model_name='productosimg',
            name='productos_img',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ProveedoresApp.proveedoresmodel'),
        ),
    ]
