# Generated by Django 3.1.5 on 2021-03-22 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProveedoresApp', '0007_auto_20210317_1707'),
    ]

    operations = [
        migrations.DeleteModel(
            name='productosIMG',
        ),
    ]
