# Generated by Django 3.1.5 on 2021-02-28 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categoria_empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100, verbose_name='Nombre de la categoria')),
            ],
        ),
        migrations.CreateModel(
            name='empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=50, verbose_name='Nombre de la empresa')),
                ('ciudad', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100, verbose_name='Dirección')),
                ('codigoPostal', models.CharField(max_length=5, verbose_name='Código Postal')),
                ('tfno', models.CharField(max_length=9, verbose_name='Numero de telefono')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electronico')),
                ('imagen', models.URLField()),
                ('descripcion', models.TextField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresasApp.categoria_empresa')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['created'],
            },
        ),
    ]
