# Generated by Django 3.1.5 on 2021-02-28 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresasApp', '0002_auto_20210228_1531'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria_empresa',
            options={'verbose_name': 'Categoria Empresa', 'verbose_name_plural': 'Categorias Empresa'},
        ),
    ]
