# Generated by Django 3.1.5 on 2021-03-01 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresasApp', '0004_empresa_tipo_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='imagen',
        ),
        migrations.AddField(
            model_name='empresa',
            name='logo_empresa',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Logo de la empresa'),
        ),
    ]
