# Generated by Django 3.1.5 on 2021-03-01 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresasApp', '0005_auto_20210301_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='categoria',
        ),
        migrations.AddField(
            model_name='empresa',
            name='categoria',
            field=models.ManyToManyField(to='empresasApp.categoria_empresa'),
        ),
    ]
