# Generated by Django 3.1.5 on 2021-03-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresasApp', '0006_auto_20210301_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción de la empresa'),
        ),
    ]
