# Generated by Django 3.1.5 on 2021-03-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresasApp', '0007_auto_20210302_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='descripcion',
            field=models.TextField(max_length=255),
        ),
    ]
