# Generated by Django 3.1.5 on 2021-03-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresasApp', '0008_auto_20210302_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='slug',
            field=models.SlugField(blank=True, max_length=10, unique=True),
        ),
    ]
