# Generated by Django 3.1.5 on 2021-03-02 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresasApp', '0009_empresa_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='slug',
        ),
    ]
