# Generated by Django 3.1.5 on 2021-03-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresasApp', '0010_remove_empresa_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='slug',
            field=models.SlugField(blank=True, max_length=10, unique=True),
        ),
    ]
