# Generated by Django 3.1.5 on 2021-03-03 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresasApp', '0011_empresa_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='logo_empresa',
            field=models.ImageField(blank=True, default='empresas/default.jpg', upload_to='empresas/logos', verbose_name='Logo de la empresa'),
        ),
    ]
