# Generated by Django 3.1.5 on 2021-03-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresasApp', '0012_auto_20210303_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='logo_empresa',
            field=models.ImageField(blank=True, default='empresas/default.png', upload_to='empresas/logos', verbose_name='Logo de la empresa'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='slug',
            field=models.SlugField(blank=True, max_length=15, unique=True),
        ),
    ]
