# Generated by Django 3.1.5 on 2021-03-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresasApp', '0014_empresa_cif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='CIF',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
