# Generated by Django 3.1.5 on 2021-03-04 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresasApp', '0015_auto_20210304_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='CIF',
        ),
    ]
