# Generated by Django 3.1.5 on 2021-03-04 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresasApp', '0017_empresa_cif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='slug',
            field=models.SlugField(auto_created=True, blank=True, max_length=15, unique=True),
        ),
    ]
