# Generated by Django 3.1.5 on 2021-03-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresasApp', '0020_auto_20210304_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoria_empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100, verbose_name='Nombre de la categoria')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoria Empresa',
                'verbose_name_plural': 'Categorias Empresa',
            },
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='categoria',
        ),
        migrations.AddField(
            model_name='empresa',
            name='categoria',
            field=models.ManyToManyField(to='empresasApp.categoria_empresa'),
        ),
    ]
