# Generated by Django 3.1.5 on 2021-03-08 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresasApp', '0021_auto_20210304_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='logo_empresa',
            field=models.ImageField(default='empresas/default.png', upload_to='empresas/logos', verbose_name='Logo de la empresa'),
        ),
    ]
